language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test it:test
scala:
  - 2.12.7
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
sudo: required # for setting hostname
addons:
  postgresql: 9.5
  hostname: localhost #https://github.com/travis-ci/travis-ci/issues/5227
before_script:
  - psql -f src/it/mojoz-postgresql-setup.sql -U postgres
  - cp src/it/resources/application.conf.travis src/it/resources/application.conf
  - sudo chmod +x /usr/local/bin/sbt #https://github.com/travis-ci/travis-ci/issues/7703
notifications:
  email:
    - guntiso@uniso.lv
