language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test it:test
scala:
  - 2.13.1
  - 2.12.11
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
addons:
  postgresql: 9.5
before_script:
  - psql -f src/it/mojoz-postgresql-setup.sql -U postgres
  - cp src/it/resources/application.conf.travis src/it/resources/application.conf
notifications:
  email:
    - guntiso@uniso.lv
