language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test it:test versionPolicyCheck
scala:
  - 2.13.7
  - 2.12.15
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
addons:
  postgresql: 9.6
before_script:
  - psql -f src/it/mojoz-postgresql-setup.sql -U postgres
  - cp src/it/resources/application.conf.ci src/it/resources/application.conf
notifications:
  email:
    - guntiso@uniso.lv
