mv src/test/resources/case-classes-out-produced.scala     src/test/resources/case-classes-out.scala
mv src/test/resources/classes-out-produced.scala          src/test/resources/classes-out.scala
mv src/test/resources/tables-out-cassandra-produced.cql   src/test/resources/tables-out-cassandra.cql
mv src/test/resources/tables-out-cassandra-produced.yaml  src/test/resources/tables-out-cassandra.yaml
mv src/test/resources/tables-out-h2-produced.sql          src/test/resources/tables-out-h2.sql
mv src/test/resources/tables-out-oracle-produced.sql      src/test/resources/tables-out-oracle.sql
mv src/test/resources/tables-out-postgresql-produced.sql  src/test/resources/tables-out-postgresql.sql
mv src/test/resources/tables-out-hsqldb-produced.sql      src/test/resources/tables-out-hsqldb.sql
mv src/test/resources/tables-out-produced.yaml            src/test/resources/tables-out.yaml
mv src/test/resources/views-out-produced.yaml             src/test/resources/views-out.yaml
mv src/test/resources/xsd-bindings-out-produced.xjb       src/test/resources/xsd-bindings-out.xjb
mv src/test/resources/xsd-out-produced.xsd                src/test/resources/xsd-out.xsd
