name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB:        mojoz
          POSTGRES_PASSWORD:  mojoz
          POSTGRES_USER:      mojoz
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Configure integration tests
      run:  cp src/it/resources/application.conf.ci src/it/resources/application.conf
    - name: Compile and test and check version policy
      run:  sbt clean update +compile +test +it:test +versionPolicyCheck
