name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB:        mojoz
          POSTGRES_PASSWORD:  mojoz
          POSTGRES_USER:      mojoz
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Configure it tests
      run:  cp src/it/resources/application.conf.ci src/it/resources/application.conf
    - name: Compile and test and check version policy
      run:  sbt clean update +compile +test +it:test +versionPolicyCheck
